/**
 * Writing src/resorts/graphs.js.
 *
 * The point of the pipeline is that adding a resort is a config file and a
 * command. That falls apart if someone then has to remember to import the
 * generated module by hand, so this regenerates the import list from what is
 * actually on disk after every build.
 *
 * Static imports rather than a Vite glob, because the same file is imported by
 * plain Node in `npm test`.
 */
import { readdir, writeFile } from "node:fs/promises";

const OUT_DIR = new URL("../../src/resorts/", import.meta.url);

/**
 * Monterosa's hand-typed graph is the fallback for that one id only. Every
 * other resort exists only if the pipeline built it — inventing a fallback for
 * one would be exactly the invented data this pipeline replaces.
 */
const BUILT_IN = { monterosa: "../resort.js" };

export async function writeRegistry() {
  const generated = (await readdir(OUT_DIR))
    .filter((f) => f.endsWith(".js") && !["index.js", "graphs.js"].includes(f) && !f.endsWith(".test.js"))
    .map((f) => f.replace(/\.js$/, ""))
    .sort();

  // A generated module wins over the built-in: once Monterosa has been built
  // from OSM, the hand-typed graph is the older, less accurate one.
  const sources = new Map(generated.map((id) => [id, `./${id}.js`]));
  for (const [id, path] of Object.entries(BUILT_IN)) {
    if (!sources.has(id)) sources.set(id, path);
  }
  const ids = [...sources.keys()].sort();

  const lines = ids.map((id) => {
    const path = sources.get(id);
    const note = path.startsWith("../")
      ? "  // The built-in hand-typed graph, until the pipeline has built this one."
      : null;
    return (note ? `${note}\n` : "") + `import * as ${id} from "${path}";`;
  });

  const module = `/**
 * Which module holds which resort's graph.
 *
 * GENERATED. Regenerated by \`npm run resort\` after every successful build, so
 * a new resort needs a config file and a workflow run, not an edit here.
 *
 * The imports are static on purpose. \`import.meta.glob\` would do this in one
 * line, but it is a Vite feature and this file is also imported by plain Node
 * in \`npm test\`; a generated list of explicit imports works in both and is
 * something you can read.
 */

${lines.join("\n")}

export const GRAPHS = { ${ids.join(", ")} };

/** The graph module for a resort id, or null if there is no data for it. */
export const graphFor = (id) => GRAPHS[id] ?? null;

/** Every resort with a graph behind it. */
export const withGraphs = () => Object.keys(GRAPHS);
`;

  await writeFile(new URL("graphs.js", OUT_DIR), module);
  return ids;
}
