/**
 * Which module holds which resort's graph.
 *
 * GENERATED. Regenerated by `npm run resort` after every successful build, so
 * a new resort needs a config file and a workflow run, not an edit here.
 *
 * The imports are static on purpose. `import.meta.glob` would do this in one
 * line, but it is a Vite feature and this file is also imported by plain Node
 * in `npm test`; a generated list of explicit imports works in both and is
 * something you can read.
 */

  // The built-in hand-typed graph, until the pipeline has built this one.
import * as monterosa from "../resort.js";

export const GRAPHS = { monterosa };

/** The graph module for a resort id, or null if there is no data for it. */
export const graphFor = (id) => GRAPHS[id] ?? null;

/** Every resort with a graph behind it. */
export const withGraphs = () => Object.keys(GRAPHS);
